### ISSUE TITLE
Bar code scanner is not working on some devices

### ISSUE THREAD

**Issue by Elvinra** [ekreutz/react-native-barcode-scanner-google#28]
On Huawai P10

I have that error on adb logcat

> 05-15 09:53:58.479  9095  9297 W DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
> 05-15 09:53:58.482  3145  4218 W ProviderHelper: Unknown dynamite feature vision.dynamite.barcode
> 05-15 09:53:58.484  9095  9297 I DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
> 05-15 09:53:58.484  9095  9297 D BarcodeNativeHandle: Cannot load feature, fall back to load whole module.
> 05-15 09:53:58.485  9095  9297 W DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
> 05-15 09:53:58.488  9095  9297 I DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
> 05-15 09:53:58.488  9095  9297 I DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
> 05-15 09:53:58.492  9095  9297 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000031/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk
> 05-15 09:53:58.493  9095  9297 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/00000031/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: Failed to validate DexClassLoader.
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib, /product/lib]]
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ddb.loadClass(:com.google.android.gms@12673025@12.6.73 (040408-194189626):3)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at day.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):22)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):84)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):52)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):117)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):114)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ryk.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):13)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@12673025@12.6.73 (040408-194189626):18)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at ryf.onTransact(:com.google.android.gms@12673025@12.6.73 (040408-194189626):12)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at android.os.Binder.transact(Binder.java:605)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.internal.stable.zza.transactAndReadException(Unknown Source:7)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.dynamite.IDynamiteLoader$Stub$Proxy.createModuleContext(Unknown Source:14)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source:63)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:31)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:218)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source:71)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.internal.vision.zzl.isOperational(Unknown Source:0)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:2)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:16)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at com.ekreutz.barcodescanner.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1267)
> 05-15 09:53:58.493  9095  9297 E ChimeraFileApk: 	at java.lang.Thread.run(Thread.java:784)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: Failed to load code for module FileApk(/data/user_de/0/com.google.android.gms/app_chimera/m/00000031/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: ddp: Failed to load code for /data/user_de/0/com.google.android.gms/app_chimera/m/00000031/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at day.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):23)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):84)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):52)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):117)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):114)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ryk.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):13)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@12673025@12.6.73 (040408-194189626):18)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at ryf.onTransact(:com.google.android.gms@12673025@12.6.73 (040408-194189626):12)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at android.os.Binder.transact(Binder.java:605)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.internal.stable.zza.transactAndReadException(Unknown Source:7)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.IDynamiteLoader$Stub$Proxy.createModuleContext(Unknown Source:14)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source:63)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:31)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:218)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source:71)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.internal.vision.zzl.isOperational(Unknown Source:0)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:2)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:16)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at com.ekreutz.barcodescanner.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1267)
> 05-15 09:53:58.493  9095  9297 E ChimeraModuleLdr: 	at java.lang.Thread.run(Thread.java:784)
> 05-15 09:53:58.493  9095  9297 W ChimeraDebugLogger: Singleton logger instance not set.
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: Failed to create module context.
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: ddp: Failed to load code for /data/user_de/0/com.google.android.gms/app_chimera/m/00000031/DynamiteModulesA_GmsCore_prodmnc_xxhdpi_release.apk
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at day.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):23)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):84)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):52)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):117)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ddn.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):114)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ryk.a(:com.google.android.gms@12673025@12.6.73 (040408-194189626):13)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@12673025@12.6.73 (040408-194189626):18)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at ryf.onTransact(:com.google.android.gms@12673025@12.6.73 (040408-194189626):12)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at android.os.Binder.transact(Binder.java:605)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.internal.stable.zza.transactAndReadException(Unknown Source:7)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.dynamite.IDynamiteLoader$Stub$Proxy.createModuleContext(Unknown Source:14)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source:63)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:31)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:218)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source:71)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.internal.vision.zzl.isOperational(Unknown Source:0)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:2)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:16)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at com.ekreutz.barcodescanner.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1267)
> 05-15 09:53:58.493  9095  9297 E DynamiteLoaderV2: 	at java.lang.Thread.run(Thread.java:784)
> 05-15 09:53:58.494  9095  9297 W DynamiteModule: Failed to load remote module: Failed to load remote module.
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: Error Loading module
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Remote load failed. No local fallback found.
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:315)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.internal.vision.zzl.zzp(Unknown Source:71)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.internal.vision.zzl.isOperational(Unknown Source:0)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:2)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:16)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.ekreutz.barcodescanner.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1267)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at java.lang.Thread.run(Thread.java:784)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to load remote module.
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source:77)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source:31)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:218)
> 05-15 09:53:58.494  9095  9297 E BarcodeNativeHandle: 	... 6 more

**Comment by Elvinra** [comment]
and its working fine on an samsung

**Comment by srolija** [comment]
A bit late, but had the same issue; related to following bug in Google Play Services:
https://issuetracker.google.com/issues/80454351
https://github.com/googlesamples/android-vision/issues/352

With global rollout, it should have been fixed on its own.

**Comment by grillermo** [comment]
I'm getting a similar

2019-04-23 15:59:43.103 20846-27845/mx.myapp.providers.dev E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source:28)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source:9)
        at com.google.android.gms.internal.vision.zzg.zza(Unknown Source:5)
        at com.google.android.gms.vision.barcode.BarcodeDetector.detect(Unknown Source:17)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source:11)
        at com.google.android.gms.vision.barcodereader.ui.camera.CameraSource$FrameProcessingRunnable.run(CameraSource.java:1166)
        at java.lang.Thread.run(Thread.java:764)

**Comment by darkknightsds** [comment]
Getting same on LGE Nexus 5, Android 6.0.1, API 23

```
08-12 11:32:00.374 11093-11241/com.jaguarlandrover.jlr_adts_sample_android E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: Remote load failed. No local fallback found.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to load remote module.
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source) 
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source) 
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source) 
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
        at com.google.android.gms.dynamic.ObjectWrapper.unwrap(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source) 
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source) 
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source) 
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by darkknightsds** [comment]
Getting same on LGE Nexus 5, Android 6.0.1, API 23

```
08-12 11:32:00.374 11093-11241/com.myproject E/BarcodeNativeHandle: Error Loading module
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: Remote load failed. No local fallback found.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source)
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source)
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source)
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to load remote module.
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source) 
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source) 
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source) 
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IBinder com.google.android.gms.dynamic.IObjectWrapper.asBinder()' on a null object reference
        at com.google.android.gms.dynamic.ObjectWrapper.unwrap(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.zzb(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source) 
        at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source) 
        at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source) 
        at com.google.android.gms.vision.Detector.receiveFrame(Unknown Source) 
        at com.google.android.gms.vision.CameraSource$zzb.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by srolija** [comment]
Since `RNCamera` now includes the high-performance barcode scanning based on MLKit which replaced the Google Vision API (now deprecated, used int this library); I would highly recommend anyone to check that integration; to get you started faster here is the code that shows usage.

https://gist.github.com/srolija/f5ab14ea720eb0e00efa3ca9e490fb3c
