### ISSUE TITLE
IllegalAccessError

### ISSUE THREAD

**Issue by Santei** [ekreutz/react-native-barcode-scanner-google#29]
Hi guys, 

I am not sure if this is worth creating an issue but I have not changed the code for BarcodeScanner since Thursday but today running the code locally I run into this error. Can someone please help.

```
java.lang.IllegalAccessError: Class com.google.android.gms.dynamic.zzg extended by class com.google.android.gms.vision.barcode.internal.client.zzd$zz
java.lang.IllegalAccessError: Class com.google.android.gms.dynamic.zzg extended by class com.google.android.gms.vision.barcode.internal.client.zzd$zza is inaccessible (declaration of 'com.google.android.gms.vision.barcode.internal.client.zzd$zza' appears in /data/app/com.paygoordersapp-IDqZ3GMc74WXRk0pTznQVQ==/base.apk)
        at com.google.android.gms.vision.barcode.BarcodeDetector$Builder.build(Unknown Source:0)
        at com.ekreutz.barcodescanner.ui.BarcodeScannerView.createBarcodeDetector(BarcodeScannerView.java:304)
        at com.ekreutz.barcodescanner.ui.BarcodeScannerView.createCameraSource(BarcodeScannerView.java:280)
        at com.ekreutz.barcodescanner.ui.BarcodeScannerView.start(BarcodeScannerView.java:168)
        at com.ekreutz.barcodescanner.ui.BarcodeScannerView.onAttachedToWindow(BarcodeScannerView.java:157)
        at android.view.View.dispatchAttachedToWindow(View.java:17486)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3337)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3344)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3344)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4988)
        at android.view.ViewGroup.addView(ViewGroup.java:4779)
        at com.facebook.react.views.view.ReactViewGroup.addView(ReactViewGroup.java:433)
        at android.view.ViewGroup.addView(ViewGroup.java:4719)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:247)
        at com.facebook.react.views.view.ReactViewManager.addView(ReactViewManager.java:38)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:401)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:822)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:929)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:989)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:786)
        at android.view.Choreographer.doFrame(Choreographer.java:718)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by Santei** [comment]
@ekreutz and other great contributors to this library. I actually noticed that I was working on the forked version of the library. Now I am working on the correct one, and while it is not longer crashing after adding `google-play-services` vision library, it still is not launching the scan view:

I am getting the following issue:
```
 { [Error: Attempted to RESUME barcode scanner before scanner view was instantiated.] framesToPop: 1, code: '2' }

"/data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so" unused DT entry: type 0x7ffffffd arg 0x76d
    /data/data/com.google.android.gms/app_vision/barcode/libs/armeabi-v7a/libbarhopper.so: is missing DT_SONAME will use basename as a replacement: "libbarhopper.so"
05-29 16:32:34.095 25419-25419/com.paygoordersapp W/zygote: Unsupported class loader
```

**Comment by Sangrene** [comment]
+1

**Comment by Sangrene** [comment]
Solved by updating google vision version to the latest as follow :
    `implementation 'com.google.android.gms:play-services-vision:15.0.2'`
